feat: add file adapter
node-casbin/file-adapter pull request #1
Opened 2021-04-28 12:33 UTC by Zxilly

Signed-off-by: Zxilly <zhouxinyu1001@gmail.com>

2021-04-28 12:33 UTC, Zxilly commented
@nodece @hsluoyz plz review

2021-04-28 12:43 UTC, hsluoyz requested changes

2021-04-28 12:43 UTC, hsluoyz commented on .gitignore
> -# Logs
Don't remove

2021-04-28 16:22 UTC, hsluoyz approved these changes

2021-04-28 16:22 UTC, merged

2021-04-28 16:23 UTC, hsluoyz commented
@Zxilly setup semantic-release

2021-04-29 08:42 UTC, Zxilly commented
@hsluoyz I will first add unit tests